server:
  port: 8090

telegram:
  webhook-path: https://9424-31-148-165-111.ngrok.io
  bot-name: applicationforcompetition_bot
  bot-token: 5821134281:AAEVvI-IlsEjbgkSXYrgS1So8YUnaOiXQmw
  api-url : https://api.telegram.org/

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ariza
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: never




